<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BG3Neuro.App</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BG3Neuro.Core\BG3Neuro.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>